/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.unsafepointer.word_count

import kotlin.test.Test
import kotlin.test.assertNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNull(null, "null should be null")
    }
}
